### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pykong** [benslavin/django-db-prefix#4]
@benslavin 
Thank you for putting up `django-db-prefix`!
For Django users like myself, it solves a simple but important problem.
And it still works with Django 2.x!

However, the project does not receive much attention from you as its sole maintainer.
And such attention has not been required so far.

Still, I like to add a new feature #2 
And overhaul the readme #3 

In case you do not have the time to review the PRs, maybe you like to grant me push access to this repo so I can refurbish it myself.

**Comment by benslavin** [comment]
@pykong I am not pursuing active development of this repository; however, there are several others who have continued its work.

You can see the full list of those who have created forks at https://github.com/benslavin/django-db-prefix/network/members

It would appear that @fingul took the liberty of [submitting the project to PyPI](https://pypi.org/project/django-db-prefix/) several years ago, so I would recommend [fingul's repository](https://github.com/fingul/django-db-prefix) as your starting point.

**Comment by benslavin** [comment]
Another quick note @pykong - it looks like the repo that's on PyPI removed the ability to specify prefixes on a per-app and per-model basis. The commits don't mention any bugs with these features, but also don't mention why they were removed.

If this functionality is important to you, you may not want to use those forks.

**Comment by pykong** [comment]
@benslavin 
Thank you for providing directions. 
Indeed I have mistaken this repo for the one active on PyPi. My bad.

Maybe you could add a single sentence to the README to inform about its current maintenance status.
